[default]
src = 'contracts'
out = 'artifacts'
libs = ['lib', 'node_modules']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
